# stages:
#   - build
#   - deploy

# variables:
#   IMAGE_TAG: latest

# before_script:
#   - apk add --no-cache python3 py3-pip
#   - pip3 install --upgrade pip
#   - pip3 install awscli

# build:
#   stage: build
#   image: docker:20.10.17
#   services:
#     - docker:20.10.17-dind
#   script:
#     - python3 -m venv venv
#     - source venv/bin/activate
#     - aws ecr get-login-password --region $AWS_DEFAULT_REGION
#     - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
#     - docker build -t raygun3491/s3upload:$IMAGE_TAG .
#     - docker push raygun3491/s3upload:$IMAGE_TAG
#   only:
#     - main

# deploy:
#   stage: deploy
#   image: python:3.8-alpine
#   script:
#     - pip install --upgrade awscli
#     - aws ecs update-service --cluster $CI_AWS_ECS_CLUSTER --service $CI_AWS_ECS_SERVICE --force-new-deployment
#   only:
#     - main

stages:
  - build
  - test
  - docker
  - deploy

###################
### Build stage ###
###################
backend-build:
  stage: build
  image: node
  script:
    - echo "Start building backend"
    - npm install
    - echo "Build backend successfully!"
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      - build/
      - node_modules/
  only:
    - main
    - develop

##################
### Test stage ###
##################
backend-test:
  stage: test
  image: node
  script:
    - echo "Start testing backend"
    - npm run test
    - echo "Test backend successfully!"
  only:
    - main
    - develop

####################
### Docker stage ###
####################
backend-docker:
  stage: docker
  image: docker:stable
  services:
    - docker:dind
  script:
    - echo "Start building docker"
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker build -t raygun3491/s3upload:latest .
    - docker push raygun3491/s3upload:latest
    - echo "Building docker successfully!"
  only:
    - main
####################
### Deploy stage ###
####################
backend-deploy:
  stage: deploy
  image: google/cloud-sdk:latest
  before_script:
    - mkdir -p ~/.ssh
    - chmod 600 $SSH_PRIVATE_KEY
    - eval $(ssh-agent -s)
    - ssh-add $SSH_PRIVATE_KEY
  script:
    - gcloud auth activate-service-account --key-file=${GCP_JSON}
    - gcloud compute ssh --zone "$GCLOUD_COMPUTE_ZONE" "$GCP_VM_HOST" --project "$GCLOUD_PROJECT_ID" --command "docker-compose up -d --build"
    - gcloud compute ssh --zone "$GCLOUD_COMPUTE_ZONE" "$GCP_VM_HOST" --project "$GCLOUD_PROJECT_ID" --command "docker image prune -f || true"
  only:
    - main
# ####################
# ### Deploy stage ###
# ####################
# backend-deploy:
#   stage: deploy
#   image: gitlab/dind:latest
#   before_script:
#     - eval $(ssh-agent -s)
#     - chmod 400 "$SSH_PRIVATE_KEY"
#     - ssh-add "$SSH_PRIVATE_KEY"
#     - mkdir -p ~/.ssh
#     - chmod 700 ~/.ssh
#   script:
#     - ssh ${GCE_LOGIN_USER}@${GCP_VM_HOST} docker images && \ docker ps -a
#     - ssh ${GCE_LOGIN_USER}@${GCP_VM_HOST} docker compose down
#     - ssh ${GCE_LOGIN_USER}@${GCP_VM_HOST} docker compose up -d
#     - ssh ${GCE_LOGIN_USER}@${GCP_VM_HOST} docker image prune -f || true
#   only:
#     - main
